from math import isclose

from pylatro.rng import (
    PseudorandomState,
    _seeded_random,
    _seeded_random_string,
    _seeded_shuffle_indices,
    pseudohash,
)


def test_pseudohash_and_pseudoseed_match_reference_fixture() -> None:
    state = PseudorandomState("AAAAAAAA")

    assert isclose(pseudohash("AAAAAAAA"), 0.43257138351543745)
    assert isclose(state.pseudoseed("boss"), 0.5374444774613187)
    assert isclose(state.pseudoseed("Voucher1"), 0.5290234269488188)
    assert isclose(state.pseudoseed("Tag1"), 0.2909399952510187)
    assert isclose(state.pseudoseed("shuffle"), 0.6564266916414188)
    assert isclose(state.pseudoseed("rarity1"), 0.4462461409768187)


# Ground truth below was generated by running Balatro's own pseudohash /
# pseudoseed / pseudorandom / pseudoshuffle / random_string functions under a
# real LuaJIT interpreter (the runtime Balatro ships with). Every comparison is
# exact: the engine must be bit-identical to the game or seeds diverge.


def test_luajit_math_random_floats_are_bit_exact() -> None:
    # math.randomseed(s); math.random() x3 under LuaJIT.
    expected = {
        0.0: (0.79420629243124097, 0.69885246563716397, 0.59010374172810343),
        0.5: (0.09657393438653461, 0.96226945770684003, 0.52150907845154126),
        0.123456789: (0.79918423337772637, 0.73692115160461924, 0.75116979792352723),
        0.987654321: (0.25286425173077731, 0.4565937988470492, 0.75742282091250512),
    }
    from pylatro import rng as rng_mod

    for seed, (a, b, c) in expected.items():
        assert _seeded_random(seed) == a
        assert rng_mod._rng.random() == b
        assert rng_mod._rng.random() == c


def test_luajit_math_random_ints_are_bit_exact() -> None:
    # math.randomseed(s); skip 3 floats; math.random(1, 52); math.random(17).
    expected = {0.0: (40, 2), 0.5: (8, 12), 0.123456789: (45, 12), 0.987654321: (5, 16)}
    from pylatro import rng as rng_mod

    for seed, (d, e) in expected.items():
        _seeded_random(seed)
        rng_mod._rng.random()
        rng_mod._rng.random()
        assert rng_mod._rng.randint(1, 52) == d
        assert rng_mod._rng.randint(1, 17) == e


def test_pseudoseed_sequence_for_seed_47xzsxlh() -> None:
    assert pseudohash("47XZSXLH") == 0.32229559968141075
    state = PseudorandomState("47XZSXLH")
    expected = {
        "Voucher1": (0.47088886429745536, 0.26246485405870534),
        "Voucher2": (0.62490725813890535, 0.52804067114650532),
        "Tarot1": (0.63711464433465537, 0.54909001780300537),
        "Joker1": (0.3618490449756554, 0.57444614805075545),
        "shuffle": (0.17243793424870538, 0.24784223249115539),
        "boss": (0.56027224293355538, 0.41658971683185536),
        "skip_1": (0.39567969077035536, 0.63278074806475537),
    }
    for key, (first, second) in expected.items():
        assert state.pseudoseed(key) == first
        assert state.pseudoseed(key) == second


def test_pseudorandom_draws_for_seed_47xzsxlh() -> None:
    state = PseudorandomState("47XZSXLH")
    assert state.pseudorandom("lucky_money") == 0.041033394483295682
    assert state.pseudorandom("stdset", 0, 25) == 2
    assert state.pseudorandom("cardrank", 1, 13) == 11


def test_pseudoshuffle_52_cards_for_seed_47xzsxlh() -> None:
    state = PseudorandomState("47XZSXLH")
    order = _seeded_shuffle_indices(52, state.pseudoseed("shuffle"))
    shuffled = [list(range(1, 53))[i - 1] for i in order]
    # fmt: off
    assert shuffled == [
        16, 3, 6, 25, 8, 42, 4, 41, 32, 48, 46, 26, 13, 7, 17, 50, 51, 39,
        18, 22, 44, 20, 27, 2, 49, 9, 31, 36, 30, 24, 21, 43, 28, 14, 23, 5,
        19, 33, 29, 10, 38, 45, 34, 52, 1, 15, 47, 37, 11, 40, 12, 35,
    ]
    # fmt: on


def test_random_string_matches_luajit() -> None:
    assert _seeded_random_string(8, 0.42)[0] == "A9B2M1XG"
    assert _seeded_random_string(8, 0.32229559968141075)[0] == "F4RES87L"


def test_seed_47xzsxlh_matches_real_game_observations() -> None:
    # Verified by playing seed 47XZSXLH in Balatro itself: the ante-1 shop
    # voucher is Hieroglyph, and skipping the Big blind gives a Rare Tag
    # (on a profile with everything discovered).
    from pylatro.data import load_game_data
    from pylatro.run import create_run_state
    from pylatro.seedsearch import unlock_data

    state = create_run_state("47XZSXLH", data=unlock_data(load_game_data()))
    assert state.current_voucher == "v_hieroglyph"
    assert state.round_resets.blind_tags == {"Small": "tag_boss", "Big": "tag_rare"}
