[program:pylatro-training]
environment=PROC_NAME="%(program_name)s"
command=/workspace/pylatro/scripts/run_ppo_v14_safe_tarot_seal_strategy.sh
autostart=true
autorestart=unexpected
startsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
