"""Constants and enumerations for the Balatro agent."""

from __future__ import annotations
from enum import IntEnum, StrEnum

# Sequence / observation constants
MAX_SEQ_LEN = 160
TOKEN_DIM = 12
SCALAR_DIM = 9  # includes pending action id for select-cards mode

MAX_JOKER_SLOTS = 8
MAX_CONSUMABLE_SLOTS = 5
MAX_SHOP_ITEMS = 10
MAX_PACK_CARDS = 5
MAX_DECK_CARDS = 62
MAX_HAND_SIZE = MAX_DECK_CARDS
MAX_VOUCHERS = 4
MAX_HAND_LEVELS = 12
MAX_PLAY_CANDIDATES = 16
MAX_DISCARD_CANDIDATES = 16
MAX_HAND_CANDIDATES = MAX_PLAY_CANDIDATES + MAX_DISCARD_CANDIDATES

POKER_HAND_NAMES = (
    "Flush Five",
    "Flush House",
    "Five of a Kind",
    "Straight Flush",
    "Four of a Kind",
    "Full House",
    "Flush",
    "Straight",
    "Three of a Kind",
    "Two Pair",
    "Pair",
    "High Card",
)


class SubPhase(StrEnum):
    BLIND_SELECT = "blind_select"
    CHOOSE_ACTION = "choose_action"
    SELECT_CARDS = "select_cards"
    SHOP = "shop"
    BOOSTER_PACK = "booster_pack"
    CONSUMABLE_TARGET = "consumable_target"


_BLIND_PLAY = 0
_BLIND_SKIP = 1
_BLIND_REROLL = 2
_PLAY_SELECTION = 3
_DISCARD_SELECTION = 4
_USE_CONSUMABLE = 5
_SELECT_CARD_START = _USE_CONSUMABLE + 1
_SELECT_CARD_END = _SELECT_CARD_START + MAX_HAND_SIZE - 1
_SELECTION_CONFIRM = _SELECT_CARD_END + 1
_SELECTION_CANCEL = _SELECTION_CONFIRM + 1
_CONSUMABLE_SLOT_START = _SELECTION_CANCEL + 1
_CONSUMABLE_SLOT_END = _CONSUMABLE_SLOT_START + MAX_CONSUMABLE_SLOTS - 1
_CONSUMABLE_HAND_TARGET_START = _CONSUMABLE_SLOT_END + 1
_CONSUMABLE_HAND_TARGET_END = _CONSUMABLE_HAND_TARGET_START + MAX_HAND_SIZE - 1
_CONSUMABLE_JOKER_TARGET_START = _CONSUMABLE_HAND_TARGET_END + 1
_CONSUMABLE_JOKER_TARGET_END = _CONSUMABLE_JOKER_TARGET_START + MAX_JOKER_SLOTS - 1
_CONSUMABLE_CONFIRM = _CONSUMABLE_JOKER_TARGET_END + 1
_CONSUMABLE_CANCEL = _CONSUMABLE_CONFIRM + 1
_SHOP_BUY_START = _CONSUMABLE_CANCEL + 1
_SHOP_BUY_END = _SHOP_BUY_START + MAX_SHOP_ITEMS - 1
_SHOP_REROLL = _SHOP_BUY_END + 1
_SHOP_SELL_JOKER_START = _SHOP_REROLL + 1
_SHOP_SELL_JOKER_END = _SHOP_SELL_JOKER_START + MAX_JOKER_SLOTS - 1
_SHOP_SELL_CONSUMABLE_START = _SHOP_SELL_JOKER_END + 1
_SHOP_SELL_CONSUMABLE_END = _SHOP_SELL_CONSUMABLE_START + MAX_CONSUMABLE_SLOTS - 1
_SHOP_LEAVE = _SHOP_SELL_CONSUMABLE_END + 1
_PACK_CLAIM_START = _SHOP_LEAVE + 1
_PACK_CLAIM_END = _PACK_CLAIM_START + MAX_PACK_CARDS - 1
_PACK_SKIP = _PACK_CLAIM_END + 1


class ActionRange(IntEnum):
    """Starting index of each action group."""
    BLIND_PLAY = _BLIND_PLAY
    BLIND_SKIP = _BLIND_SKIP
    BLIND_REROLL = _BLIND_REROLL
    PLAY_SELECTION = _PLAY_SELECTION
    DISCARD_SELECTION = _DISCARD_SELECTION
    USE_CONSUMABLE = _USE_CONSUMABLE
    SELECT_CARD_START = _SELECT_CARD_START
    SELECT_CARD_END = _SELECT_CARD_END
    SELECTION_CONFIRM = _SELECTION_CONFIRM
    SELECTION_CANCEL = _SELECTION_CANCEL
    CONSUMABLE_SLOT_START = _CONSUMABLE_SLOT_START
    CONSUMABLE_SLOT_END = _CONSUMABLE_SLOT_END
    CONSUMABLE_HAND_TARGET_START = _CONSUMABLE_HAND_TARGET_START
    CONSUMABLE_HAND_TARGET_END = _CONSUMABLE_HAND_TARGET_END
    CONSUMABLE_JOKER_TARGET_START = _CONSUMABLE_JOKER_TARGET_START
    CONSUMABLE_JOKER_TARGET_END = _CONSUMABLE_JOKER_TARGET_END
    CONSUMABLE_CONFIRM = _CONSUMABLE_CONFIRM
    CONSUMABLE_CANCEL = _CONSUMABLE_CANCEL
    SHOP_BUY_START = _SHOP_BUY_START
    SHOP_BUY_END = _SHOP_BUY_END
    SHOP_REROLL = _SHOP_REROLL
    SHOP_SELL_JOKER_START = _SHOP_SELL_JOKER_START
    SHOP_SELL_JOKER_END = _SHOP_SELL_JOKER_END
    SHOP_SELL_CONSUMABLE_START = _SHOP_SELL_CONSUMABLE_START
    SHOP_SELL_CONSUMABLE_END = _SHOP_SELL_CONSUMABLE_END
    SHOP_LEAVE = _SHOP_LEAVE
    PACK_CLAIM_START = _PACK_CLAIM_START
    PACK_CLAIM_END = _PACK_CLAIM_END
    PACK_SKIP = _PACK_SKIP


NUM_ACTIONS = int(ActionRange.PACK_SKIP) + 1


# Token type IDs
class TokenType(IntEnum):
    OBJ = 0
    META = 1
    DECK = 2
    JOKER = 3
    VOUCHER = 4
    CONSUMABLE = 5
    SHOP = 6
    BLIND_SELECT = 7
    HAND_LEVEL = 8
    HAND_CANDIDATE = 9
    PAD = 10


# Token position ranges (start positions)
OBJ_START = 0
META_START = 1
META_COUNT = 9
DECK_START = 10
DECK_MAX = 62
JOKER_START = 72
JOKER_MAX = 8
VOUCHER_START = 80
VOUCHER_MAX = 4
CONSUMABLE_START = 84
CONSUMABLE_MAX = 5
SHOP_START = 89
SHOP_MAX = 10
BLIND_SELECT_START = 99
BLIND_SELECT_MAX = 3
HAND_LEVEL_START = 102
HAND_LEVEL_MAX = 12
HAND_CANDIDATE_START = 114
HAND_CANDIDATE_MAX = 32
PAD_START = 146
